development:
  SECRET_KEY_BASE: 282b9c745072749d1804adaa9b083ba4df26278e86304b1768073a22ff6236b68ce8df62c30b5d355724858195639cb25c12d44eb05344779712efcc3bce0ab7
  DATABASE_NAME: unicheck
  DATABASE_HOSTNAME: localhost
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: mylove0210
  EMAIL: lamdo
  EMAIL_PASSWORD: mylove0210
  ADMIN_EMAIL: toughmen93@gmail.com
test:
  SECRET_KEY_BASE: 282b9c745072749d1804adaa9b083ba4df26278e86304b1768073a22ff6236b68ce8df62c30b5d355724858195639cb25c12d44eb05344779712efcc3bce0ab7
  DATABASE_NAME: test_unicheck
  DATABASE_HOSTNAME: localhost
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: mylove0210
  EMAIL: lamdo
  EMAIL_PASSWORD: mylove0210
  ADMIN_EMAIL: toughmen93@gmail.com
production:
  SECRET_KEY_BASE: 282b9c745072749d1804adaa9b083ba4df26278e86304b1768073a22ff6236b68ce8df62c30b5d355724858195639cb25c12d44eb05344779712efcc3bce0ab7
  DATABASE_NAME: unicheck
  DATABASE_HOSTNAME: heroku
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: mylove0210
  EMAIL: lamdo
  EMAIL_PASSWORD: mylove0210
  ADMIN_EMAIL: toughmen93@gmail.com
