development:
  SECRET_KEY_BASE: 282b9c745072749d1804adaa9b083ba4df26278e86304b1768073a22ff6236b68ce8df62c30b5d355724858195639cb25c12d44eb05344779712efcc3bce0ab7
  DATABASE_NAME: "dnlblog"
  DATABASE_HOSTNAME: "localhost"
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "password"
test:
  SECRET_KEY_BASE: 282b9c745072749d1804adaa9b083ba4df26278e86304b1768073a22ff6236b68ce8df62c30b5d355724858195639cb25c12d44eb05344779712efcc3bce0ab7
  DATABASE_NAME: "test_dnlblog"
  DATABASE_HOSTNAME: "localhost"
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: "password"
